In [1]:
import pandas as pd

#df = pd.read_parquet(
#    "../data/raw/raw_data.parquet"
#)
#this is commented because it caused many problems, maybe im just a bad programmer
print(df.shape)
df.head(20)

(29578, 8)

,review_id,review,voted_up,votes_up,timestamp_created,refunded,playtime_at_review,language
0,232591722,this game is good yes but if you have a bad wi...,False,0,1786465751,False,1578,english
1,232591709,game crashed when anticheat is launched... spe...,False,0,1786465738,False,3178,english
2,232591636,balls,True,0,1786465674,False,701,english
3,232591267,♥♥♥♥ game.,False,0,1786465354,False,9929,english
4,232588494,buggy piece of ♥♥♥♥,False,0,1786462936,False,2582,english
5,232587775,just i like it,True,0,1786462273,False,841,english
6,232586800,IO,True,0,1786461385,False,331,english
7,232585606,Division 7 versus Division 4 is unfair; it's t...,False,0,1786460317,False,5627,english
8,232584454,very fun \r\nbut litel lag,True,0,1786459257,False,3675,english
9,232584328,"Game dosent run, drops to 10 fps and isnt play...",False,0,1786459164,False,216,english
10,232584230,JB,True,0,1786459076,False,434,english
11,232582196,Oyunu biraz oynadım ve hiç benlik bir oyun olm...,False,0,1786457239,False,109258,english
12,232578579,Error gak jelas,False,0,1786453550,False,2854,english
13,232577462,"just download FIFA 17, don't buy this sht",False,0,1786452315,False,377,english
14,232577401,cheaters,False,0,1786452236,False,2876,english
15,232576646,I miss the old Fifa,False,0,1786451395,False,3752,english
16,232576541,the game sucks bc instead of packing 99 zidane...,False,0,1786451273,False,2445,english
17,232576379,ball,False,0,1786451085,False,4010,english
18,232576093,"""unable to connect to EA servers"" THE MOST ♥♥♥...",False,0,1786450719,False,15988,english
19,232575434,"Got it fairly cheap on sale, still regretting ...",False,0,1786449935,False,931,english

In [2]:
df['timestamp_created'] = pd.to_datetime(df['timestamp_created'], unit='s')
df['playtime_at_review'] = (df['playtime_at_review'] / 60).round(1)
df.head()

,review_id,review,voted_up,votes_up,timestamp_created,refunded,playtime_at_review,language
0,232591722,this game is good yes but if you have a bad wi...,False,0,2026-08-11 16:29:11,False,26.3,english
1,232591709,game crashed when anticheat is launched... spe...,False,0,2026-08-11 16:28:58,False,53.0,english
2,232591636,balls,True,0,2026-08-11 16:27:54,False,11.7,english
3,232591267,♥♥♥♥ game.,False,0,2026-08-11 16:22:34,False,165.5,english
4,232588494,buggy piece of ♥♥♥♥,False,0,2026-08-11 15:42:16,False,43.0,english

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29578 entries, 0 to 29577
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   review_id           29578 non-null  str
 1   review              29578 non-null  str
 2   voted_up            29578 non-null  bool
 3   votes_up            29578 non-null  int64
 4   timestamp_created   29578 non-null  datetime64[s]
 5   refunded            29578 non-null  bool
 6   playtime_at_review  29578 non-null  float64
 7   language            29578 non-null  str
dtypes: bool(2), datetime64[s](1), float64(1), int64(1), str(3)
memory usage: 5.5 MB

In [5]:
df = df.rename(columns={'timestamp_created': 'review_date', 'playtime_at_review': 'playtime'})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29578 entries, 0 to 29577
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    29578 non-null  str
 1   review       29578 non-null  str
 2   voted_up     29578 non-null  bool
 3   votes_up     29578 non-null  int64
 4   review_date  29578 non-null  datetime64[s]
 5   refunded     29578 non-null  bool
 6   playtime     29578 non-null  float64
 7   language     29578 non-null  str
dtypes: bool(2), datetime64[s](1), float64(1), int64(1), str(3)
memory usage: 5.5 MB

In [6]:
df.isna().sum()

review_id      0
review         0
voted_up       0
votes_up       0
review_date    0
refunded       0
playtime       0
language       0
dtype: int64

In [7]:
from langdetect import detect, LangDetectException

def detect_lang(text: str):
    try:
        return detect(str(text))
    except:
        return 'unknown'

df['language'] = df['review'].apply(detect_lang)

In [8]:
df.value_counts("language")

language
en         17573
so          2118
unknown     1022
de           843
tl           621
af           541
cy           523
pl           486
es           438
id           398
da           396
pt           370
no           369
tr           353
sw           313
ro           284
ca           252
sq           248
fi           236
et           224
it           222
fr           189
nl           189
vi           186
sk           166
hr           166
sl           150
ar           147
sv            97
lt            93
hu            81
lv            57
cs            50
ru            49
fa            42
th            32
he            14
ur            14
zh-cn          8
bg             5
ko             4
el             4
uk             3
ja             1
mk             1
Name: count, dtype: int64

In [9]:
df = df.drop(df[(df["language"] != "en") & (df["language"] != "so") & (df["language"] != "unknown")].index)
df.value_counts("language")

language
en         17573
so          2118
unknown     1022
Name: count, dtype: int64

In [10]:
(df['voted_up'].value_counts(normalize=True) * 100).round(1)

voted_up
False    57.3
True     42.7
Name: proportion, dtype: float64

In [11]:
# df.to_parquet("../data/processed/processed_data.parquet")
# this again