In [1]:
import pandas as pd

df = pd.read_parquet(
    "../data/raw/raw_data.parquet"
)

print(df.shape)
df.head()

(29576, 9)

,Unnamed: 0,review_id,review,voted_up,votes_up,timestamp_created,refunded,playtime_at_review,language
0,0,232591722,this game is good yes but if you have a bad wi...,False,0,1786465751,False,1578,en
1,1,232591709,game crashed when anticheat is launched... spe...,False,0,1786465738,False,3178,en
2,2,232591636,balls,True,0,1786465674,False,701,no
3,3,232591267,♥♥♥♥ game.,False,0,1786465354,False,9929,lt
4,4,232588494,buggy piece of ♥♥♥♥,False,0,1786462936,False,2582,en

In [2]:
df['timestamp_created'] = pd.to_datetime(df['timestamp_created'], unit='s').dt.strftime('%d-%m-%Y')
df['playtime_at_review'] = (df['playtime_at_review'] / 60).round(1)
df.head()

,Unnamed: 0,review_id,review,voted_up,votes_up,timestamp_created,refunded,playtime_at_review,language
0,0,232591722,this game is good yes but if you have a bad wi...,False,0,11-08-2026,False,26.3,en
1,1,232591709,game crashed when anticheat is launched... spe...,False,0,11-08-2026,False,53.0,en
2,2,232591636,balls,True,0,11-08-2026,False,11.7,no
3,3,232591267,♥♥♥♥ game.,False,0,11-08-2026,False,165.5,lt
4,4,232588494,buggy piece of ♥♥♥♥,False,0,11-08-2026,False,43.0,en

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 29576 entries, 0 to 29577
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          29576 non-null  int64
 1   review_id           29576 non-null  int64
 2   review              29576 non-null  str
 3   voted_up            29576 non-null  bool
 4   votes_up            29576 non-null  int64
 5   timestamp_created   29576 non-null  str
 6   refunded            29576 non-null  bool
 7   playtime_at_review  29576 non-null  float64
 8   language            29576 non-null  str
dtypes: bool(2), float64(1), int64(3), str(3)
memory usage: 5.9 MB

In [4]:
df = df.drop(columns=["Unnamed: 0"])
df = df.rename(columns={'timestamp_created': 'review_date', 'playtime_at_review': 'playtime'})
df.info()

<class 'pandas.DataFrame'>
Index: 29576 entries, 0 to 29577
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    29576 non-null  int64
 1   review       29576 non-null  str
 2   voted_up     29576 non-null  bool
 3   votes_up     29576 non-null  int64
 4   review_date  29576 non-null  str
 5   refunded     29576 non-null  bool
 6   playtime     29576 non-null  float64
 7   language     29576 non-null  str
dtypes: bool(2), float64(1), int64(2), str(3)
memory usage: 5.6 MB

In [5]:
df.isna().sum()

review_id      0
review         0
voted_up       0
votes_up       0
review_date    0
refunded       0
playtime       0
language       0
dtype: int64

In [9]:
from langdetect import detect, LangDetectException

def detect_lang(text: str):
    try:
        return detect(str(text))
    except:
        return 'unknown'

df['language'] = df['review'].apply(detect_lang)

In [10]:
df.value_counts("language")

language
en         17574
so          2117
unknown     1022
de           847
tl           634
af           538
cy           517
pl           486
es           442
da           391
id           390
pt           366
no           359
tr           355
sw           315
ro           285
ca           256
sq           247
fi           234
et           228
it           220
fr           195
nl           193
vi           187
sk           164
hr           162
sl           157
ar           146
sv            93
lt            91
hu            79
lv            58
cs            50
ru            49
fa            42
th            32
ur            15
he            14
zh-cn          8
bg             5
el             4
ko             3
uk             3
ja             1
zh-tw          1
mk             1
Name: count, dtype: int64

In [11]:
df.to_parquet("../data/processed/processed_data.parquet")